spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: nurtas05
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update